export const SessionStatus = Object.freeze({
  CREATED: 'CREATED',
  WAITING_FOR_FIRST_JOIN: 'WAITING_FOR_FIRST_JOIN',
  ROUND_ACTIVE: 'ROUND_ACTIVE',
  REPLAY_WAITING: 'REPLAY_WAITING',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED'
});

export const RoundStatus = Object.freeze({
  WAITING_FOR_FIRST_JOIN: 'WAITING_FOR_FIRST_JOIN',
  JOIN_WINDOW_OPEN: 'JOIN_WINDOW_OPEN',
  READY_CHECK: 'READY_CHECK',
  DISTRIBUTING: 'DISTRIBUTING',
  SWAP_OPEN: 'SWAP_OPEN',
  SWAP_CLOSED: 'SWAP_CLOSED',
  REVEALING: 'REVEALING',
  ROUND_ENDED: 'ROUND_ENDED',
  ROUND_CANCELLED: 'ROUND_CANCELLED'
});

export const SwapState = Object.freeze({
  NONE: 'NONE',
  KEPT: 'KEPT',
  PENDING: 'PENDING',
  MATCHED: 'MATCHED',
  UNMATCHED: 'UNMATCHED'
});

export const ParticipationLabel = Object.freeze({
  REGISTERED_ABSENT: 'REGISTERED_ABSENT',
  JOINED_ACTIVE: 'JOINED_ACTIVE',
  DISCONNECTED: 'DISCONNECTED',
  RECONNECTED: 'RECONNECTED',
  ROUND_COMPLETE: 'ROUND_COMPLETE'
});

export const ClientMessageType = Object.freeze({
  HELLO: 'HELLO',
  PONG: 'PONG',
  ROUND_READY: 'ROUND_READY',
  SWAP_REQUEST: 'SWAP_REQUEST',
  KEEP_BOX: 'KEEP_BOX',
  PRE_RESULT_READY: 'PRE_RESULT_READY'
});

export const ServerMessageType = Object.freeze({
  WELCOME: 'WELCOME',
  SESSION_SNAPSHOT: 'SESSION_SNAPSHOT',
  JOIN_WINDOW_STARTED: 'JOIN_WINDOW_STARTED',
  READY_CHECK_STARTED: 'READY_CHECK_STARTED',
  ROUND_STARTED: 'ROUND_STARTED',
  BOX_ASSIGNED: 'BOX_ASSIGNED',
  SWAP_WINDOW_OPEN: 'SWAP_WINDOW_OPEN',
  SWAP_PENDING: 'SWAP_PENDING',
  SWAP_MATCHED: 'SWAP_MATCHED',
  SWAP_UNMATCHED: 'SWAP_UNMATCHED',
  SWAP_WINDOW_CLOSED: 'SWAP_WINDOW_CLOSED',
  REVEAL_START: 'REVEAL_START',
  PLAYER_RESULT: 'PLAYER_RESULT',
  ROUND_RESULTS: 'ROUND_RESULTS',
  REPLAY_WAITING: 'REPLAY_WAITING',
  REPLAY_ACCEPTED: 'REPLAY_ACCEPTED',
  SESSION_ENDED: 'SESSION_ENDED',
  ERROR: 'ERROR',
  PING: 'PING'
});

export const WebhookEventType = Object.freeze({
  SESSION_CREATED: 'session.created',
  PLAYER_JOINED: 'player.joined',
  PLAYER_DISCONNECTED: 'player.disconnected',
  PLAYER_RECONNECTED: 'player.reconnected',
  ROUND_JOIN_WINDOW_STARTED: 'round.join_window_started',
  ROUND_STARTED: 'round.started',
  ROUND_CANCELLED: 'round.cancelled',
  ROUND_SWAP_MATCHED: 'round.swap_matched',
  ROUND_ENDED: 'round.ended',
  SESSION_REPLAY_WAITING: 'session.replay_waiting',
  SESSION_REPLAY_STARTED: 'session.replay_started',
  SESSION_ENDED: 'session.ended'
});
